version: '3.4'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - '5433:5432'
    expose:
      - '5432'
    networks:
    - layanancerdas

  layanan_cerdas_api:
    build: 
      context: .
    depends_on:
      - postgres
    environment: 
      APP_NAME: layanan_cerdas
      VERSION: 1.0.0
      PORT: 3030
      HOST: 0.0.0.0
      DB_USERNAME: postgres
      DB_PASSWORD: admin
      DB_HOSTNAME: postgres
      DB_PORT: 5432
      DB_NAME: layanan_cerdas
      DB_DIALECT: postgres
      ACCESS_TOKEN_KEY: d0aa9c33de488cfc8ed3f9fce5c3b264bf965279d023ee10a9d93b5369c9ecd4cd5ed2cb89fd7cae380e4f8c16ff32d0a2e96b925414ee8cb03e01281710413f
      ACCESS_TOKEN_AGE: 6h
      CLOUD_NAME: 'dnvltueqb'
      API_KEY: '131712519741951'
      API_SECRET: 'hj0ZgOKOwG8l5o8vpnSwPtR6US0'
      MAILER_SMTP_HOST: smtp.mailtrap.io
      MAILER_SMTP_PORT: 465
      MAILER_SECURE: false
      MAILER_AUTH_USER: e7944463ded79f
      MAILER_AUTH_PASSWORD: e2d82fa7b1e8f9
      MAILER_SENDER_NAME: layananCerdas
      MAILER_SENDER_EMAIL: noreaplylayanancerdas@mail.com
      
    ports:
      - '3030:3030'
    expose:
      - '3030'
    networks:
    - layanancerdas
    

networks:
  layanancerdas:
    driver: bridge